### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by dreadmaps** [TomCosaert/FoundryVTT-ICRPG#10]
Any chance we can have a notes tab for the NPC type of character that had a public notes section and a GMs only section? Making journal entries for each is time consuming to link so just a thought

**Comment by TomCosaert** [comment]
Hey @dreadmaps Thanks, but as mentioned on the front page, this project has been abandoned. See [this fork](https://github.com/jessev14/FoundryVTT-ICRPG/) for continued development and further improvements.
I maintained this project up to ICRPG version 1.2.4 which was at that time compatible with Foundry VTT version 8.8.0.
