### ISSUE TITLE
Ability text bug

### ISSUE THREAD

**Issue by Spiderfoxtail** [TomCosaert/FoundryVTT-ICRPG#11]
Hello, I was programming ABILITIES into my table and discovered that the DESCRIPTION was not appearing when I hit save. When going back to edit, the text is saved, but disappears once I hit save.

I am running:
Foundry VTT Version 10 - Build 285
ICRPG Version 3.3.0
No Modules

I have provided an image below for reference of the bug.

![AbilityBugICRPG01](https://user-images.githubusercontent.com/46890287/190214969-f5d86059-c79f-4f70-9961-5cfab20e5c99.png)

**Comment by Spiderfoxtail** [comment]
Update: I also just noticed that the notes section of the character sheet has the same issue.

**Comment by TomCosaert** [comment]
Hey @Spiderfoxtail Thanks, but as mentioned on the front page, this project has been abandoned. See [this fork](https://github.com/jessev14/FoundryVTT-ICRPG/) for continued development and further improvements. 
I maintained this project up to ICRPG version **1.2.4** which was at that time compatible with Foundry VTT version **8.8.0**.
