### ISSUE TITLE
Effort Rolls in 1E Actor Sheet Throws Error

### ISSUE THREAD

**Issue by victoriussinger** [TomCosaert/FoundryVTT-ICRPG#7]
When rolling effort rolls in the 1E Actor Sheet, every type except Magic (1d8) throws an errow.
There seems to be an error with the roll formula for this sheet, but there's no problem with the 2E Actor Sheet.
See screenshot of the console output in Chrome.

![ICRPG Bug Report](https://user-images.githubusercontent.com/49375932/108819420-1f560f80-75bb-11eb-8884-ae478f5886fc.png)

**Comment by TomCosaert** [comment]
Well spotted! Thanks for the pull request (merged) and putting the "effort" into this issue! ;-)

**Comment by victoriussinger** [comment]
Great pun ;-) Thanks for the quick response! Glad to contribute to this well-crafted system for ICRPG.
